"""'add_changefileinfo_reviewinfo_mergestatus'

Revision ID: f3a382076205
Revises: df5a70dbdda7
Create Date: 2019-12-26 17:35:06.111966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a382076205'
down_revision = 'df5a70dbdda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pull_number', sa.Integer(), nullable=False),
    sa.Column('project', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reviewer', sa.VARCHAR(length=100), nullable=False),
    sa.Column('review_description', sa.TEXT(), nullable=True),
    sa.Column('review_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('create_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.add_column('pull_request', sa.Column('merged', sa.BOOLEAN(), nullable=False))
    op.alter_column('pull_request', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('request_file', sa.Column('additions', sa.BIGINT(), nullable=True))
    op.add_column('request_file', sa.Column('changes', sa.BIGINT(), nullable=True))
    op.add_column('request_file', sa.Column('deletions', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_file', 'deletions')
    op.drop_column('request_file', 'changes')
    op.drop_column('request_file', 'additions')
    op.alter_column('pull_request', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('pull_request', 'merged')
    op.drop_table('reviews')
    # ### end Alembic commands ###
