
repo_return_content = """
{
    "id": 2126244,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMTI2MjQ0",
    "name": "bootstrap",
    "full_name": "twbs/bootstrap",
    "private": false,
    "owner": {
        "login": "twbs",
        "id": 2918581,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjI5MTg1ODE=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/2918581?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/twbs",
        "html_url": "https://github.com/twbs",
        "followers_url": "https://api.github.com/users/twbs/followers",
        "following_url": "https://api.github.com/users/twbs/following{/other_user}",
        "gists_url": "https://api.github.com/users/twbs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/twbs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/twbs/subscriptions",
        "organizations_url": "https://api.github.com/users/twbs/orgs",
        "repos_url": "https://api.github.com/users/twbs/repos",
        "events_url": "https://api.github.com/users/twbs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/twbs/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "html_url": "https://github.com/twbs/bootstrap",
    "description": "The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.",
    "fork": false,
    "url": "https://api.github.com/repos/twbs/bootstrap",
    "forks_url": "https://api.github.com/repos/twbs/bootstrap/forks",
    "keys_url": "https://api.github.com/repos/twbs/bootstrap/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/twbs/bootstrap/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/twbs/bootstrap/teams",
    "hooks_url": "https://api.github.com/repos/twbs/bootstrap/hooks",
    "issue_events_url": "https://api.github.com/repos/twbs/bootstrap/issues/events{/number}",
    "events_url": "https://api.github.com/repos/twbs/bootstrap/events",
    "assignees_url": "https://api.github.com/repos/twbs/bootstrap/assignees{/user}",
    "branches_url": "https://api.github.com/repos/twbs/bootstrap/branches{/branch}",
    "tags_url": "https://api.github.com/repos/twbs/bootstrap/tags",
    "blobs_url": "https://api.github.com/repos/twbs/bootstrap/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/twbs/bootstrap/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/twbs/bootstrap/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/twbs/bootstrap/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/twbs/bootstrap/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/twbs/bootstrap/languages",
    "stargazers_url": "https://api.github.com/repos/twbs/bootstrap/stargazers",
    "contributors_url": "https://api.github.com/repos/twbs/bootstrap/contributors",
    "subscribers_url": "https://api.github.com/repos/twbs/bootstrap/subscribers",
    "subscription_url": "https://api.github.com/repos/twbs/bootstrap/subscription",
    "commits_url": "https://api.github.com/repos/twbs/bootstrap/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/twbs/bootstrap/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/twbs/bootstrap/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/twbs/bootstrap/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/twbs/bootstrap/contents/{+path}",
    "compare_url": "https://api.github.com/repos/twbs/bootstrap/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/twbs/bootstrap/merges",
    "archive_url": "https://api.github.com/repos/twbs/bootstrap/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/twbs/bootstrap/downloads",
    "issues_url": "https://api.github.com/repos/twbs/bootstrap/issues{/number}",
    "pulls_url": "https://api.github.com/repos/twbs/bootstrap/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/twbs/bootstrap/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/twbs/bootstrap/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/twbs/bootstrap/labels{/name}",
    "releases_url": "https://api.github.com/repos/twbs/bootstrap/releases{/id}",
    "deployments_url": "https://api.github.com/repos/twbs/bootstrap/deployments",
    "created_at": "2011-07-29T21:19:00Z",
    "updated_at": "2019-07-04T00:53:23Z",
    "pushed_at": "2019-07-03T20:10:11Z",
    "git_url": "git://github.com/twbs/bootstrap.git",
    "ssh_url": "git@github.com:twbs/bootstrap.git",
    "clone_url": "https://github.com/twbs/bootstrap.git",
    "svn_url": "https://github.com/twbs/bootstrap",
    "homepage": "https://getbootstrap.com",
    "size": 143727,
    "stargazers_count": 134370,
    "watchers_count": 134370,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "forks_count": 65939,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 363,
    "license": {
        "key": "mit",
        "name": "MIT License",
        "spdx_id": "MIT",
        "url": "https://api.github.com/licenses/mit",
        "node_id": "MDc6TGljZW5zZTEz"
    },
    "forks": 65939,
    "open_issues": 363,
    "watchers": 134370,
    "default_branch": "master",
    "organization": {
        "login": "twbs",
        "id": 2918581,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjI5MTg1ODE=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/2918581?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/twbs",
        "html_url": "https://github.com/twbs",
        "followers_url": "https://api.github.com/users/twbs/followers",
        "following_url": "https://api.github.com/users/twbs/following{/other_user}",
        "gists_url": "https://api.github.com/users/twbs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/twbs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/twbs/subscriptions",
        "organizations_url": "https://api.github.com/users/twbs/orgs",
        "repos_url": "https://api.github.com/users/twbs/repos",
        "events_url": "https://api.github.com/users/twbs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/twbs/received_events",
        "type": "Organization",
        "site_admin": false
    },
    "network_count": 65939,
    "subscribers_count": 7286
}

"""

pull_return_content = """

"""

info_dict = '''
[{'page': 1, 'info': {'title': 'Update .eslintrc.json', 'number': 28985, 'state': 'closed', 'description': '', 'user_name': 'guofushan', 'user_id': 48540932, 'created_at': '2019-07-04T07:37:22Z'}}, {'page': 1, 'info': {'title': 'Update .eslintrc.json', 'number': 28985, 'state': 'closed', 'description': '', 'user_name': 'guofushan', 'user_id': 48540932, 'created_at': '2019-07-04T07:37:22Z'}}, {'page': 2, 'info': {'title': 'Add ARIA search landmark to documentation.', 'number': 28983, 'state': 'closed', 'description': "Reference: [WAI-ARIA Authoring Practices 1.1 § 4.3.8](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_search).\r\n\r\nAddendum: `.bd-sidebar` and `bd-toc` don't appear to have enough roles, but I'm new at this whole ARIA thing so would prefer advice on this one.", 'user_name': 'bardiharborow', 'user_id': 1073681, 'created_at': '2019-07-02T14:56:57Z'}}, {'page': 2, 'info': {'title': 'Add ARIA search landmark to documentation.', 'number': 28983, 'state': 'closed', 'description': "Reference: [WAI-ARIA Authoring Practices 1.1 § 4.3.8](https://www.w3.org/TR/wai-aria-practices-1.1/#aria_lh_search).\r\n\r\nAddendum: `.bd-sidebar` and `bd-toc` don't appear to have enough roles, but I'm new at this whole ARIA thing so would prefer advice on this one.", 'user_name': 'bardiharborow', 'user_id': 1073681, 'created_at': '2019-07-02T14:56:57Z'}}, {'page': 3, 'info': {'title': 'Master ysds addition subtraction func', 'number': 28978, 'state': 'closed', 'description': '', 'user_name': 'varshasachan', 'user_id': 40065578, 'created_at': '2019-06-30T13:46:52Z'}}, {'page': 3, 'info': {'title': 'Master ysds addition subtraction func', 'number': 28978, 'state': 'closed', 'description': '', 'user_name': 'varshasachan', 'user_id': 40065578, 'created_at': '2019-06-30T13:46:52Z'}}, {'page': 4, 'info': {'title': 'Master mc checkbox radio align', 'number': 28974, 'state': 'closed', 'description': '', 'user_name': 'varshasachan', 'user_id': 40065578, 'created_at': '2019-06-28T02:53:31Z'}}, {'page': 4, 'info': {'title': 'Master mc checkbox radio align', 'number': 28974, 'state': 'closed', 'description': '', 'user_name': 'varshasachan', 'user_id': 40065578, 'created_at': '2019-06-28T02:53:31Z'}}, {'page': 5, 'info': {'title': 'Fix pre color', 'number': 28966, 'state': 'closed', 'description': 'Fixes #28925', 'user_name': 'MartijnCuppens', 'user_id': 11559216, 'created_at': '2019-06-26T09:39:05Z'}}, {'page': 5, 'info': {'title': 'Fix pre color', 'number': 28966, 'state': 'closed', 'description': 'Fixes #28925', 'user_name': 'MartijnCuppens', 'user_id': 11559216, 'created_at': '2019-06-26T09:39:05Z'}}, {'page': 6, 'info': {'title': 'Stretched link updates', 'number': 28958, 'state': 'closed', 'description': '- Remove IE10 background hack\r\n- Ability to change the pseudo element\r\n- Ability to change the z-index\r\n- Remove pointer events, just inherit this', 'user_name': 'MartijnCuppens', 'user_id': 11559216, 'created_at': '2019-06-25T12:40:09Z'}}, {'page': 6, 'info': {'title': 'Stretched link updates', 'number': 28958, 'state': 'closed', 'description': '- Remove IE10 background hack\r\n- Ability to change the pseudo element\r\n- Ability to change the z-index\r\n- Remove pointer events, just inherit this', 'user_name': 'MartijnCuppens', 'user_id': 11559216, 'created_at': '2019-06-25T12:40:09Z'}}, {'page': 7, 'info': {'title': 'Added Line Height Utility', 'number': 28955, 'state': 'closed', 'description': '', 'user_name': 'glass9', 'user_id': 52164276, 'created_at': '2019-06-24T13:50:05Z'}}, {'page': 7, 'info': {'title': 'Added Line Height Utility', 'number': 28955, 'state': 'closed', 'description': '', 'user_name': 'glass9', 'user_id': 52164276, 'created_at': '2019-06-24T13:50:05Z'}}, {'page': 8, 'info': {'title': 'Allow .page-links to get left margin.', 'number': 28948, 'state': 'open', 'description': 'Give the choice to set a left-margin to pagination links.', 'user_name': 'GeoSot', 'user_id': 22406063, 'created_at': '2019-06-24T07:54:22Z'}}, {'page': 8, 'info': {'title': 'Allow .page-links to get left margin.', 'number': 28948, 'state': 'open', 'description': 'Give the choice to set a left-margin to pagination links.', 'user_name': 'GeoSot', 'user_id': 22406063, 'created_at': '2019-06-24T07:54:22Z'}}, {'page': 9, 'info': {'title': 'Change invalid icon from cross to exclamation mark', 'number': 28944, 'state': 'closed', 'description': 'The cross icon was confusing since some browsers use it as a reset button.\r\n\r\nThe svg is handcrafted by myself.\r\n\r\nFixes #28440\r\n\r\nDemo: https://deploy-preview-28944--twbs-bootstrap.netlify.com/docs/4.3/components/forms/#server-side', 'user_name': 'MartijnCuppens', 'user_id': 11559216, 'created_at': '2019-06-22T10:05:51Z'}}, {'page': 9, 'info': {'title': 'Change invalid icon from cross to exclamation mark', 'number': 28944, 'state': 'closed', 'description': 'The cross icon was confusing since some browsers use it as a reset button.\r\n\r\nThe svg is handcrafted by myself.\r\n\r\nFixes #28440\r\n\r\nDemo: https://deploy-preview-28944--twbs-bootstrap.netlify.com/docs/4.3/components/forms/#server-side', 'user_name': 'MartijnCuppens', 'user_id': 11559216, 'created_at': '2019-06-22T10:05:51Z'}}, {'page': 10, 'info': {'title': 'Fix group list items borders overlapping', 'number': 28940, 'state': 'closed', 'description': 'This PR fixes an issue with overlapping of group list items borders (e.g. in case of RGBA border color & transparent item background).\r\nHere is a [pen](https://codepen.io/kvlsrg/pen/QXpWRZ).\r\n', 'user_name': 'kvlsrg', 'user_id': 17578344, 'created_at': '2019-06-21T12:03:05Z'}}, {'page': 10, 'info': {'title': 'Fix group list items borders overlapping', 'number': 28940, 'state': 'closed', 'description': 'This PR fixes an issue with overlapping of group list items borders (e.g. in case of RGBA border color & transparent item background).\r\nHere is a [pen](https://codepen.io/kvlsrg/pen/QXpWRZ).\r\n', 'user_name': 'kvlsrg', 'user_id': 17578344, 'created_at': '2019-06-21T12:03:05Z'}}]

'''